FROM tabulario/iceberg-rest:1.6.0
ADD --chmod=644 https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/8.0.33/mysql-connector-j-8.0.33.jar /usr/lib/iceberg-rest/mysql-connector-j-8.0.33.jar
CMD ["java", "-cp", "iceberg-rest-image-all.jar:mysql-connector-j-8.0.33.jar", "org.apache.iceberg.rest.RESTCatalogServer"]
